version: '3.3'
services:
  mysql:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=banking
        POSTGRES_INITDB_ARGS="--encoding=UTF8 --locale=en_US.UTF-8"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./data/postgres/postgres.conf:/var/lib/postgresql/data/postgresql.conf
      - ./data/postgres/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
      - ./data/postgres/pg_ident.conf:/var/lib/postgresql/data/pg_ident.conf
